### ISSUE TITLE
ALT Image Descriptions Bubble is Default Color

### ISSUE THREAD

**Issue by fleurite** [AprilSylph/Palettes-for-Tumblr#105]
### Platform

Windows 10 Home version 21H1

### Browser

Firefox 101.0.1 (64-bit)

### Addon version

v1.0.1

### Details

When Tumblr added the ability to view ALT image descriptions by pressing a button, I noticed that the shade of purple for the text bubble is not overridden by this extension. 

I use three UserStyles (via Stylus) for Tumblr on top of the Palettes extension -- two are my own which just adjust the width of the in-dashboard blog viewer and tint the hyperlinks in post bodies, and the other is [Custom Dashboard Palette by paw](https://github.com/paw/tumblr-custom-palette-userstyle). I have the same exact hex codes across both the latter UserStyle and the Palettes extension, so I can only assume that the `background-color` property does not use the same purple variable.

Due to the nature of the text bubble vanishing if one clicks anywhere outside of it, I am unable to Inspect it via my browser to find what is responsible for the color difference.

![Screenshot 2022-06-28 112728](https://user-images.githubusercontent.com/95893576/176255923-e0becfb5-9112-4ae0-821f-eef2e5ccca73.png)

**Comment by AprilSylph** [comment]
Yep, this is a Tumblr bug.
