### ISSUE TITLE
When using a different font, display [tumblr] as it appears without a font change

### ISSUE THREAD

**Issue by nobodysuspectsthebutterfly** [AprilSylph/Palettes-for-Tumblr#149]
I have no idea if there's any way of fixing this, since I can't figure out how it works in the first place, but when using the default Favorit font, [tumblr] (with the brackets) appears as a wordmark using the tumblr logo font. (In both posts and tags.)  If there were any way of keeping this option when Palettes is used to change fonts, that would be awesome. 
![image](https://user-images.githubusercontent.com/15401050/218324676-05e6c90f-cd0b-4077-8e37-a21678c6f42d.png)

**Comment by marcustyphoon** [comment]
It's part of the font. This would have to be a change to the DOM (editing in a styled span that uses Favorit for just that word, I guess?) which might not be the best idea in React. Cute idea though! Maybe there's another way.

**Comment by AprilSylph** [comment]
I don't have the expertise to pull the Tumblr ligatures out of Favorit to re-apply on top of other fonts. Even the idea is just going off my assumption on how fonts work, I might be talking nonsense!

**Comment by nobodysuspectsthebutterfly** [comment]
Ah well, it would almost certainly have to be DOM based rather than CSS, adding in a span per Marcus's idea, but I can see that's too complex for a rare usage. Thanks anyway!

**Comment by marcustyphoon** [comment]
We could try it as a userscript for funsies :D
