### ISSUE TITLE
Font size inconsistency between left and right sidebars?

### ISSUE THREAD

**Issue by paints-with-bold-colours** [AprilSylph/Palettes-for-Tumblr#158]
As seen below, the font size for the left and right sidebar are different, with the text in the leftside navigation being noticeably smaller. When I deactivated Palettes, both sidebars had the same font size. When I change the font size in Palettes, it does affect both sidebars, but the left side remains consistently smaller.
You can observe the difference in the screenshot below. (My chosen font size here is 16, if it matters)
![font-size](https://github.com/AprilSylph/Palettes-for-Tumblr/assets/79892717/acd0691b-e89b-432b-874b-d13f94bc96d6)

(Ive not used github in quite a while, please let me know if I put this in the wrong place or anything)

**Comment by AprilSylph** [comment]
The font sizes _are_ just ever so slightly different all the time, changing the base size just makes it more obvious.

**Comment by paints-with-bold-colours** [comment]
They appear to be identical size when I deactivate Palettes? I'm confused, am I missing something?
![tumblr-fonts](https://github.com/AprilSylph/Palettes-for-Tumblr/assets/79892717/f4f61339-0525-4631-b63d-17b03f688cb1)

**Comment by marcustyphoon** [comment]
I'm seeing them as both the same size with and without palettes right now. I think the font used in the right column was changed to match at some point between the creation of this issue and now? Sadly I forgot to save the page or save screenshots so I can't confirm that. But do you also observe them both being the same now with palettes on?

**Comment by paints-with-bold-colours** [comment]
Oh, huh, yeah, they're the same size now. Strange.
