### ISSUE TITLE
Tumblr 

### ISSUE THREAD

**Issue by werdna696** [AprilSylph/Palettes-for-Tumblr#162]
### Platform

Windows 10

### Browser

Microsoft edge

### Addon version

Unsure, it is the app from app store, the latest.

### Details

I am unable to save a header image or avatar image successfully always reverts to default image. 
The images are within the size specified,

**Comment by AprilSylph** [comment]
This is not Tumblr's support form. This is a browser extension for Tumblr's web interface.

Go to https://www.tumblr.com/support if you are having an issue with Tumblr itself.
