### ISSUE TITLE
As of right now, neither "Palettes-For-Tumblr" nor "Old Blue" on Xkit works

### ISSUE THREAD

**Issue by FierceFireDayne** [AprilSylph/Palettes-for-Tumblr#32]
### Bug description
When any palette other than "default" is selected, the entire page BG becomes totally white. Tumblr is still essentially functional like this, it's just that the primary thing this addon is meant to do, does not.

I also attempted reinstalling "Old Blue" on my Xkit and it does the exact same thing, for in case knowing that is of any use to you. Also the Xkit button is now black instead of grey on the Default look and light grey instead of dark grey on the white, again, just for if that information is helpful.

### Platform information
I'm using the latest version of Firefox (85.0.2) and the latest version of Palettes for tumblr (0.1.3) and the latest Xkit (7.9.2), at least as far as I am aware.

### Screenshots
![image](https://user-images.githubusercontent.com/79282085/108414818-99397200-7224-11eb-8e80-ae275ae84ae4.png)
![image](https://user-images.githubusercontent.com/79282085/108414857-a5253400-7224-11eb-8db8-08c914e5d338.png)
![image](https://user-images.githubusercontent.com/79282085/108414920-b4a47d00-7224-11eb-9df4-9198360299de.png)

**Comment by AprilSylph** [comment]
resolved in [v0.1.4](https://github.com/AprilSylph/Palettes-for-Tumblr/releases/tag/v0.1.4)! the update process should be automatic, but to update immediately, you can navigate to **`about:addons`**, then click the gear icon, and then "Check for Updates". you may need to reload any open Tumblr pages after the update is fetched for it to be properly applied.
