### ISSUE TITLE
Dark Mode with old Tumblr palettes (e.g. circa 2013/2016 modes)

### ISSUE THREAD

**Issue by dottiekh** [AprilSylph/Palettes-for-Tumblr#47]
Previously, Dark Reader used to work symbiotically with these two palettes. Recently, though, it is now being overwritten by this extension. It would be nice for this extension to have an option for these two specific themes if its feasible (it would essentially be the Dark Mode palette but with the old blue background color options).

**Comment by AprilSylph** [comment]
This isn't something I'm interested in doing. Palettes for Tumblr will at some point allow you to create and share your own palettes, but I won't be baking custom palettes into the addon.

In the meantime, you are free to use a general-purpose userstyle addon such as [Stylus](https://addons.mozilla.org/firefox/addon/styl-us/) to create your own palette by modifying one of the [palette stylesheets](https://github.com/AprilSylph/Palettes-for-Tumblr/tree/master/src/stylesheets).
